#ifndef LIBRARY1DEMO_GLOBAL_H
#define LIBRARY1DEMO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRARY1DEMO_LIBRARY)
#  define LIBRARY1DEMOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBRARY1DEMOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRARY1DEMO_GLOBAL_H
